sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start create a image"
  - ./gradlew build
  - docker build -t springtest ./

script:
  - docker run -e CI=true


after_success:
  - echo "success"